import autoit
import time


print('... beginning autobank automation script')

def export_letter(letter):
    autoit.send("#3")
    time.sleep(2.0)
    autoit.send("https://login.maximizer.com/MaxLogin")
    time.sleep(0.5)
    autoit.send("{ENTER}")
    time.sleep(3.0)
    autoit.mouse_move(2801, 421)
    time.sleep(1.0)
    # autoit.mouse_click(x=2287, y=278, speed=0)
    # time.sleep(3.0)
    autoit.mouse_click(x=2801, y=421, speed=0)
    time.sleep(5.0)
    autoit.mouse_click(x=2965, y=414, speed=0)
    time.sleep(5.0)

    autoit.mouse_click(x=2273, y=191, speed=0)
    time.sleep(1.0)
    autoit.mouse_click(x=2290, y=344, speed=0)
    time.sleep(1.0)
    autoit.send(letter + '{ENTER}')
    time.sleep(5.0)
    autoit.mouse_click(x=2112, y=186, speed=0)
    time.sleep(1.0)
    autoit.mouse_click(x=2165, y=475, speed=0)
    time.sleep(0.75)
    autoit.mouse_click(x=2481, y=186, speed=0)
    time.sleep(3.0)
    autoit.send('export_%s{ENTER}' % letter)
    time.sleep(2.0)
    autoit.mouse_click(x=3819, y=16, speed=0)
    time.sleep(1.0)


# export_letter('a')
# export_letter('b')
export_letter('c')
# export_letter('d')
export_letter('e')
export_letter('f')
export_letter('g')
export_letter('h')
export_letter('i')
export_letter('j')
export_letter('k')
export_letter('l')
export_letter('m')
export_letter('n')
# export_letter('o')
export_letter('p')
export_letter('q')
export_letter('r')
export_letter('s')
export_letter('t')
export_letter('u')
export_letter('v')
export_letter('w')
export_letter('x')
export_letter('y')
export_letter('z')

print('... finished successfully. Exiting')

